# Generated by Django 3.0.8 on 2020-07-22 07:09

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=10)),
                ('content_type', models.CharField(max_length=10)),
                ('content_number', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=10)),
                ('content_file', models.ImageField(upload_to=study.models.Content_1.file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Content_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=10)),
                ('content_label', models.CharField(max_length=10)),
                ('content_type', models.CharField(max_length=10)),
                ('content_number', models.CharField(max_length=5)),
                ('content_file', models.ImageField(upload_to=study.models.Content_2.file_upload_to)),
            ],
        ),
    ]
