# Generated by Django 3.0.8 on 2020-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_1',
            name='category',
        ),
        migrations.RemoveField(
            model_name='content_1',
            name='content_number',
        ),
        migrations.RemoveField(
            model_name='content_1',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='content_1',
            name='grade',
        ),
        migrations.AddField(
            model_name='content_1',
            name='content_grade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content_1',
            name='year',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content_1',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content_2',
            name='content_label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content_2',
            name='content_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content_2',
            name='content_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content_2',
            name='publisher',
            field=models.CharField(max_length=50),
        ),
    ]
