# Generated by Django 3.0.8 on 2020-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20200724_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_1',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content_1',
            name='content_number_begin',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content_1',
            name='content_number_end',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
