# Generated by Django 3.0.8 on 2020-07-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20200724_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content_2',
            old_name='content_number',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='content_2',
            old_name='content_type',
            new_name='content_chapter',
        ),
        migrations.AddField(
            model_name='content_2',
            name='content_number_begin',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content_2',
            name='content_number_end',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
