# Generated by Django 3.0.8 on 2020-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20200727_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_2',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
