# Generated by Django 3.0.8 on 2020-07-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_content_2_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_2',
            name='year',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
