# Generated by Django 3.0.8 on 2020-07-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_content_2_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_1',
            name='content_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content_2',
            name='content_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
